### ISSUE TITLE
Sistema de Pontuação

### ISSUE THREAD

**Issue by omateocortez** [PyMemory/Projeto-Integrador#1]
### Criar um sistema lógico e bem **otimizado** (em questão de tamanho rsrs) do sistema de pontuação. 

O @NicolasDeogenes já tinha criado um .txt (anexado) da ideia de como poderíamos calcular isso, quando alguém conseguir fazer isso marca essa _issue_ aqui ;) 

_Abraços virtuais,
Mateo._

🔗 [Sistema de Pontuação PyGame - PI.txt](https://github.com/PyMemory/Projeto-Integrador/files/15279022/Sistema.de.Pontuacao.PyGame.-.PI.txt)

**Comment by NicolasDeogenes** [comment]
Sistema de Pontuação já foi criado, agora precisamos fazer algumas alterações especificadas dentro dos arquivos das fases. Uma delas é vincular a função que conta quando cartas foram viradas com o método de virar a carta, a outra é criarmos uma função ou qualquer coisa que marque o final de cada fase, marcando o final do looping while que coloquei.

**Comment by NicolasDeogenes** [comment]
Sistema de Pontuação atualizado, criei um arquivo q contém a classe que calcular os pontos de cada fase, agora precisamos criar um arquivo que calcule a pontuação total, somando os pontos de cada fase.
