### ISSUE TITLE
Correção do Diagrama e do MER

### ISSUE THREAD

**Issue by omateocortez** [PyMemory/Projeto-Integrador#2]
### As relações tão certas,
só precisa dar uma olhada nas chaves primárias, estrangeiras, nos nomes das colunas e tabelas.

Não tem _muita_ pressa mas precisa ficar ligeiro, é ate **quinta que vem (16/05)**.
Melhoras @Mattcs1206, volta pra nois irmão!

Abraços virtuais,
Mateo.

**Comment by Mattcs1206** [comment]
corrigi tudo la, mas me avisa se faltou algo!!

**Comment by omateocortez** [comment]
### Fecha aqui quando tiver certo o Diagrama e o MER

**Comment by Mattcs1206** [comment]
Resolvido
