### ISSUE TITLE
Selecionadores 

### ISSUE THREAD

**Issue by HenriqueNalin** [PyMemory/Projeto-Integrador#4]
### **Tentar achar uma maneira de incluir no pygame uma "caixa" pra selecionar o conteúdo ( nome e turma ) do banco de dados.**

Se alguém que estiver com mais tempo livre que eu conseguir achar uma maneira de fazer isso coloca aqui!

**Comment by Mattcs1206** [comment]
import pygame
import sqlite3

# Inicializando o Pygame
pygame.init()

# Definindo algumas cores
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

# Tamanho da tela
WIDTH, HEIGHT = 800, 600

# Criando a janela
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Selecionar Conteúdo do Banco de Dados")

# Conectando ao banco de dados
conn = sqlite3.connect('seu_banco_de_dados.db')
c = conn.cursor()

# Função para obter os nomes e turmas do banco de dados
def obter_nomes_e_turmas():
    c.execute("SELECT nome, turma FROM alunos")
    alunos = c.fetchall()
    return alunos

# Função para desenhar a "caixa" de seleção
def desenhar_caixa_selecao(alunos):
    y_offset = 50
    for aluno in alunos:
        nome, turma = aluno
        fonte = pygame.font.Font(None, 36)
        texto = fonte.render(f"{nome} - {turma}", True, BLACK)
        texto_rect = texto.get_rect(center=(WIDTH/2, y_offset))
        screen.blit(texto, texto_rect)
        y_offset += 50

# Loop principal do jogo
running = True
while running:
    screen.fill(WHITE)
    
    # Obtendo os nomes e turmas do banco de dados
    alunos = obter_nomes_e_turmas()
    
    # Desenhando a "caixa" de seleção na tela
    desenhar_caixa_selecao(alunos)
    
    # Verificando eventos
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
            
    pygame.display.flip()
