### ISSUE TITLE
Otimização do BD - 2 Edvan's

### ISSUE THREAD

**Issue by omateocortez** [PyMemory/Projeto-Integrador#9]
To com 2 Edvan's no BD que são a mesma pessoa, mas com duas salas diferentes...

**Comment by Mattcs1206** [comment]
man isso ai eu realmente acho q nn vai dar nenhum problema, tipo a gente nem precisa mencionar isso la na apresentacao, mas bora conversar sobre isso na terca da semana q vem e decidir o course of action pra ver se a gente vai mudar ou nao(realmente acho q da nada).
